"""Thread-safe lookup: InChIKey → cross-reference IDs (KEGG/HMDB/ChEBI/LIPIDMAPS).

Backed by the pre-built aggregated sqlite at data/concord/inchikey_xref.sqlite
(generated by scripts/metagent/build_inchikey_xref.py from ChEBI + RaMP sources).

Usage::

    from concord.lookup.inchikey_xref import InchikeyXrefLookup
    lkp = InchikeyXrefLookup()
    ref = lkp.lookup("WQZGKKKJIJFFOK-GASJEMHNSA-N")
    # ref -> {"inchikey": ..., "chebi_id": ..., "kegg_id": ..., "hmdb_id": ..., "lipidmaps_id": ...}
    # or None if not found
"""
from __future__ import annotations

import sqlite3
import threading
from dataclasses import dataclass
from pathlib import Path

_DEFAULT_DB = Path(__file__).resolve().parents[2] / "data" / "concord" / "inchikey_xref.sqlite"


@dataclass(frozen=True)
class XrefRecord:
    inchikey: str
    chebi_id: str | None
    kegg_id: str | None
    hmdb_id: str | None
    lipidmaps_id: str | None


class InchikeyXrefLookup:
    """Thread-safe InChIKey → xref lookup backed by inchikey_xref.sqlite."""

    def __init__(self, db_path: str | Path | None = None) -> None:
        self._db = Path(db_path) if db_path else _DEFAULT_DB
        self._local = threading.local()
        self._available: bool | None = None

    def _conn(self) -> sqlite3.Connection | None:
        if not hasattr(self._local, "conn"):
            if not self._db.exists():
                self._local.conn = None
            else:
                conn = sqlite3.connect(str(self._db), check_same_thread=False)
                conn.row_factory = sqlite3.Row
                self._local.conn = conn
        return self._local.conn

    @property
    def available(self) -> bool:
        if self._available is None:
            self._available = self._db.exists()
        return self._available

    def lookup(self, inchikey: str) -> XrefRecord | None:
        """Return xref record for the given 27-char InChIKey, or None."""
        if not inchikey:
            return None
        conn = self._conn()
        if conn is None:
            return None
        cur = conn.cursor()
        cur.execute(
            "SELECT inchikey, chebi_id, kegg_id, hmdb_id, lipidmaps_id "
            "FROM inchikey_xref WHERE inchikey = ?",
            (inchikey.strip(),),
        )
        row = cur.fetchone()
        if row is None:
            return None
        return XrefRecord(
            inchikey=row["inchikey"],
            chebi_id=row["chebi_id"],
            kegg_id=row["kegg_id"],
            hmdb_id=row["hmdb_id"],
            lipidmaps_id=row["lipidmaps_id"],
        )
